/*==============================================================*/
/* DBMS name:      ORACLE Version 12c/23c                       */
/* Created on:     11/20/2025 - FIXED VERSION                   */
/*==============================================================*/

-- Eliminar tablas si existen (ignorar errores)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ABOGADO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CASO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CASOABOGADO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CASOETAPA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CASOETAPAABOGADO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CLIENTECONTACTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DOCUMENTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ETAPAPROCESAL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE IMPUGNACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE JUDICIALENTIDAD CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAGO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TIPODOCUMENTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TIPOPROCESO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

/*==============================================================*/
/* Table: TIPODOCUMENTO - Catálogo base                         */
/*==============================================================*/
CREATE TABLE TIPODOCUMENTO (
   ID_TIPO_DOC          VARCHAR2(2)           NOT NULL,
   DESC_TIPO_DOC        VARCHAR2(30)          NOT NULL,
   CONSTRAINT PK_TIPODOCUMENTO PRIMARY KEY (ID_TIPO_DOC)
);

/*==============================================================*/
/* Table: TIPOPROCESO - Catálogo de procesos                    */
/*==============================================================*/
CREATE TABLE TIPOPROCESO (
   TIPO_ID              NUMBER(6)             NOT NULL,
   NOMBRE_TIPO_PROCESO  VARCHAR2(50)          NOT NULL,
   CONSTRAINT PK_TIPOPROCESO PRIMARY KEY (TIPO_ID)
);

CREATE SEQUENCE SEQ_TIPOPROCESO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_TIPOPROCESO_ID
BEFORE INSERT ON TIPOPROCESO
FOR EACH ROW
BEGIN
   IF :NEW.TIPO_ID IS NULL THEN
      SELECT SEQ_TIPOPROCESO.NEXTVAL INTO :NEW.TIPO_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: JUDICIALENTIDAD                                       */
/*==============================================================*/
CREATE TABLE JUDICIALENTIDAD (
   ENTIDAD_ID           NUMBER(6)             NOT NULL,
   NOMBRE               VARCHAR2(200)         NOT NULL,
   TIPO_ENTIDAD         VARCHAR2(80),
   DIRECCION            CLOB,
   CIUDAD               VARCHAR2(100),
   DEPARTAMENTO         VARCHAR2(100),
   TELEFONO             VARCHAR2(50),
   EMAIL                VARCHAR2(100),
   CONSTRAINT PK_JUDICIALENTIDAD PRIMARY KEY (ENTIDAD_ID)
);

CREATE SEQUENCE SEQ_JUDICIALENTIDAD START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_JUDICIALENTIDAD_ID
BEFORE INSERT ON JUDICIALENTIDAD
FOR EACH ROW
BEGIN
   IF :NEW.ENTIDAD_ID IS NULL THEN
      SELECT SEQ_JUDICIALENTIDAD.NEXTVAL INTO :NEW.ENTIDAD_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: ABOGADO                                               */
/*==============================================================*/
CREATE TABLE ABOGADO (
   ABOGADO_ID           NUMBER(6)             NOT NULL,
   ID_TIPO_DOC          VARCHAR2(2)           NOT NULL,
   N_DOCUMENTO_ABOGADO  VARCHAR2(15)          NOT NULL,
   NOMBRE_ABOGADO       VARCHAR2(100)         NOT NULL,
   APELLIDO_ABOGADO     VARCHAR2(100)         NOT NULL,
   TARJETA_PROFESIONAL  VARCHAR2(50)          NOT NULL,
   ESPECIALIZACION      VARCHAR2(100),
   EMAIL_ABOGADO        VARCHAR2(100),
   TELEFONO_ABOGADO     VARCHAR2(50),
   CONSTRAINT PK_ABOGADO PRIMARY KEY (ABOGADO_ID),
   CONSTRAINT AK_DOCUMENTO_UNICO_ABOGADO UNIQUE (N_DOCUMENTO_ABOGADO),
   CONSTRAINT AK_TARJETA_UNICO_ABOGADO UNIQUE (TARJETA_PROFESIONAL),
   CONSTRAINT FK_ABOGADO_UTILIZA_D_TIPODOCU FOREIGN KEY (ID_TIPO_DOC)
      REFERENCES TIPODOCUMENTO (ID_TIPO_DOC)
);

CREATE SEQUENCE SEQ_ABOGADO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_ABOGADO_ID
BEFORE INSERT ON ABOGADO
FOR EACH ROW
BEGIN
   IF :NEW.ABOGADO_ID IS NULL THEN
      SELECT SEQ_ABOGADO.NEXTVAL INTO :NEW.ABOGADO_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: CLIENTE                                               */
/*==============================================================*/
CREATE TABLE CLIENTE (
   CLIENTE_ID           NUMBER(6)             NOT NULL,
   ID_TIPO_DOC          VARCHAR2(2)           NOT NULL,
   NOMBRE_CLIENTE       VARCHAR2(100)         NOT NULL,
   APELLIDO_CLIENTE     VARCHAR2(100)         NOT NULL,
   N_DOCUMENTO_CLIENTE  VARCHAR2(15)          NOT NULL,
   DIRECCION_NOTIFICACION CLOB,
   FECHA_NACIMIENTO     DATE,
   OBSERVACIONES        CLOB,
   CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID),
   CONSTRAINT AK_DOCUMENTO_UNICO_CLIENTE UNIQUE (N_DOCUMENTO_CLIENTE),
   CONSTRAINT FK_CLIENTE_UTILIZA_D_TIPODOCU FOREIGN KEY (ID_TIPO_DOC)
      REFERENCES TIPODOCUMENTO (ID_TIPO_DOC)
);

CREATE INDEX UTILIZA_DOCUMENTO_FK ON CLIENTE (ID_TIPO_DOC ASC);

CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLIENTE_ID
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
   IF :NEW.CLIENTE_ID IS NULL THEN
      SELECT SEQ_CLIENTE.NEXTVAL INTO :NEW.CLIENTE_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: CASO                                                  */
/*==============================================================*/
CREATE TABLE CASO (
   CASO_ID              NUMBER(6)             NOT NULL,
   CLIENTE_ID           NUMBER(6)             NOT NULL,
   TIPO_ID              NUMBER(6)             NOT NULL,
   EXPEDIENTE           VARCHAR2(60)          NOT NULL,
   FECHA_INICIO         DATE,
   FECHA_FIN            DATE,
   VALOR                NUMBER(14,2),
   ESTADO               VARCHAR2(50),
   CONSTRAINT PK_CASO PRIMARY KEY (CASO_ID),
   CONSTRAINT AK_EXPEDIENTE_UNICO_CASO UNIQUE (EXPEDIENTE),
   CONSTRAINT FK_CASO_PRESENTA_CLIENTE FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE (CLIENTE_ID),
   CONSTRAINT FK_CASO_CLASIFICA_TIPOPROC FOREIGN KEY (TIPO_ID)
      REFERENCES TIPOPROCESO (TIPO_ID)
);

CREATE INDEX PRESENTA_FK ON CASO (CLIENTE_ID ASC);
CREATE INDEX CLASIFICA_FK ON CASO (TIPO_ID ASC);

CREATE SEQUENCE SEQ_CASO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CASO_ID
BEFORE INSERT ON CASO
FOR EACH ROW
BEGIN
   IF :NEW.CASO_ID IS NULL THEN
      SELECT SEQ_CASO.NEXTVAL INTO :NEW.CASO_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: CASOABOGADO                                           */
/*==============================================================*/
CREATE TABLE CASOABOGADO (
   CASO_ABOGADO_ID      NUMBER(6)             NOT NULL,
   CASO_ID              NUMBER(6)             NOT NULL,
   ABOGADO_ID           NUMBER(6)             NOT NULL,
   ROL                  VARCHAR2(50),
   FECHA_ASIGNACION     DATE,
   FECHA_REMOCION       DATE,
   CONSTRAINT PK_CASOABOGADO PRIMARY KEY (CASO_ABOGADO_ID),
   CONSTRAINT FK_CASOABOG_ASIGNADO__CASO FOREIGN KEY (CASO_ID)
      REFERENCES CASO (CASO_ID),
   CONSTRAINT FK_CASOABOG_PARTICIPA_ABOGADO FOREIGN KEY (ABOGADO_ID)
      REFERENCES ABOGADO (ABOGADO_ID)
);

CREATE INDEX ASIGNADO_A_FK ON CASOABOGADO (CASO_ID ASC);
CREATE INDEX PARTICIPA_EN_FK ON CASOABOGADO (ABOGADO_ID ASC);

CREATE SEQUENCE SEQ_CASOABOGADO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CASOABOGADO_ID
BEFORE INSERT ON CASOABOGADO
FOR EACH ROW
BEGIN
   IF :NEW.CASO_ABOGADO_ID IS NULL THEN
      SELECT SEQ_CASOABOGADO.NEXTVAL INTO :NEW.CASO_ABOGADO_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: CASOETAPA                                             */
/*==============================================================*/
CREATE TABLE CASOETAPA (
   CASO_ETAPA_ID        NUMBER(6)             NOT NULL,
   CASO_ID              NUMBER(6)             NOT NULL,
   ENTIDAD_ID           NUMBER(6)             NOT NULL,
   FECHA_EVENTO         DATE,
   ESTADO_EVENTO        VARCHAR2(50),
   DESCRIPCION          CLOB,
   RESULTADO            CLOB,
   INSTANCIA            SMALLINT,
   CONSTRAINT PK_CASOETAPA PRIMARY KEY (CASO_ETAPA_ID),
   CONSTRAINT FK_CASOETAP_INCLUYE_E_CASO FOREIGN KEY (CASO_ID)
      REFERENCES CASO (CASO_ID),
   CONSTRAINT FK_CASOETAP_SE_REALIZ_JUDICIAL FOREIGN KEY (ENTIDAD_ID)
      REFERENCES JUDICIALENTIDAD (ENTIDAD_ID)
);

CREATE INDEX INCLUYE_ETAPA_FK ON CASOETAPA (CASO_ID ASC);
CREATE INDEX SE_REALIZA_EN_FK ON CASOETAPA (ENTIDAD_ID ASC);

CREATE SEQUENCE SEQ_CASOETAPA START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CASOETAPA_ID
BEFORE INSERT ON CASOETAPA
FOR EACH ROW
BEGIN
   IF :NEW.CASO_ETAPA_ID IS NULL THEN
      SELECT SEQ_CASOETAPA.NEXTVAL INTO :NEW.CASO_ETAPA_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: CASOETAPAABOGADO                                      */
/*==============================================================*/
CREATE TABLE CASOETAPAABOGADO (
   ID                   NUMBER(6)             NOT NULL,
   ABOGADO_ID           NUMBER(6)             NOT NULL,
   CASO_ETAPA_ID        NUMBER(6)             NOT NULL,
   ROL                  VARCHAR2(50),
   CONSTRAINT PK_CASOETAPAABOGADO PRIMARY KEY (ID),
   CONSTRAINT FK_CASOETAP_INTERVIEN_ABOGADO FOREIGN KEY (ABOGADO_ID)
      REFERENCES ABOGADO (ABOGADO_ID),
   CONSTRAINT FK_CASOETAP_ES_ATENDI_CASOETAP FOREIGN KEY (CASO_ETAPA_ID)
      REFERENCES CASOETAPA (CASO_ETAPA_ID)
);

CREATE INDEX INTERVIENE_EN_FK ON CASOETAPAABOGADO (ABOGADO_ID ASC);
CREATE INDEX ES_ATENDIDA_POR_FK ON CASOETAPAABOGADO (CASO_ETAPA_ID ASC);

CREATE SEQUENCE SEQ_CASOETAPAABOGADO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CASOETAPAABOGADO_ID
BEFORE INSERT ON CASOETAPAABOGADO
FOR EACH ROW
BEGIN
   IF :NEW.ID IS NULL THEN
      SELECT SEQ_CASOETAPAABOGADO.NEXTVAL INTO :NEW.ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: CLIENTECONTACTO                                       */
/*==============================================================*/
CREATE TABLE CLIENTECONTACTO (
   CONTACTO_ID          NUMBER(6)             NOT NULL,
   CLIENTE_ID           NUMBER(6)             NOT NULL,
   TIPO_CONTACTO        VARCHAR2(30),
   DESC_CONTACTO        VARCHAR2(200),
   OBSERVACION          VARCHAR2(200),
   CONSTRAINT PK_CLIENTECONTACTO PRIMARY KEY (CONTACTO_ID),
   CONSTRAINT FK_CLIENTEC_TIENE_CON_CLIENTE FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE (CLIENTE_ID)
);

CREATE INDEX TIENE_CONTACTO_FK ON CLIENTECONTACTO (CLIENTE_ID ASC);

CREATE SEQUENCE SEQ_CLIENTECONTACTO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLIENTECONTACTO_ID
BEFORE INSERT ON CLIENTECONTACTO
FOR EACH ROW
BEGIN
   IF :NEW.CONTACTO_ID IS NULL THEN
      SELECT SEQ_CLIENTECONTACTO.NEXTVAL INTO :NEW.CONTACTO_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: DOCUMENTO                                             */
/*==============================================================*/
CREATE TABLE DOCUMENTO (
   DOCUMENTO_ID         NUMBER(6)             NOT NULL,
   CASO_ETAPA_ID        NUMBER(6)             NOT NULL,
   NOMBRE_ORIGINAL      VARCHAR2(250),
   TIPO_MIME            VARCHAR2(100),
   RUTA_ARCHIVO         VARCHAR2(500),
   USUARIO_SUBIDA       VARCHAR2(100),
   DESCRIPCION          CLOB,
   CONSTRAINT PK_DOCUMENTO PRIMARY KEY (DOCUMENTO_ID),
   CONSTRAINT FK_DOCUMENT_ADJUNTA_D_CASOETAP FOREIGN KEY (CASO_ETAPA_ID)
      REFERENCES CASOETAPA (CASO_ETAPA_ID)
);

CREATE INDEX ADJUNTA_DOCUMENTO_FK ON DOCUMENTO (CASO_ETAPA_ID ASC);

CREATE SEQUENCE SEQ_DOCUMENTO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_DOCUMENTO_ID
BEFORE INSERT ON DOCUMENTO
FOR EACH ROW
BEGIN
   IF :NEW.DOCUMENTO_ID IS NULL THEN
      SELECT SEQ_DOCUMENTO.NEXTVAL INTO :NEW.DOCUMENTO_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: ETAPAPROCESAL                                         */
/*==============================================================*/
CREATE TABLE ETAPAPROCESAL (
   ETAPA_ID             NUMBER(6)             NOT NULL,
   TIPO_ID              NUMBER(6)             NOT NULL,
   NOMBRE_ETAPA_PROCESAL VARCHAR2(80)         NOT NULL,
   ORDEN                SMALLINT,
   CONSTRAINT PK_ETAPAPROCESAL PRIMARY KEY (ETAPA_ID),
   CONSTRAINT FK_ETAPAPRO_DEFINE_ET_TIPOPROC FOREIGN KEY (TIPO_ID)
      REFERENCES TIPOPROCESO (TIPO_ID)
);

CREATE INDEX DEFINE_ETAPAS_FK ON ETAPAPROCESAL (TIPO_ID ASC);

CREATE SEQUENCE SEQ_ETAPAPROCESAL START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_ETAPAPROCESAL_ID
BEFORE INSERT ON ETAPAPROCESAL
FOR EACH ROW
BEGIN
   IF :NEW.ETAPA_ID IS NULL THEN
      SELECT SEQ_ETAPAPROCESAL.NEXTVAL INTO :NEW.ETAPA_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: IMPUGNACION                                           */
/*==============================================================*/
CREATE TABLE IMPUGNACION (
   IMPUGNACION_ID       NUMBER(6)             NOT NULL,
   CASO_ETAPA_ID        NUMBER(6)             NOT NULL,
   TIPO_RECURSO         VARCHAR2(100),
   FECHA_PRESENTACION   DATE,
   INSTANCIA_DESTINO    SMALLINT,
   ESTADO               VARCHAR2(50),
   OBSERVACIONES        CLOB,
   CONSTRAINT PK_IMPUGNACION PRIMARY KEY (IMPUGNACION_ID),
   CONSTRAINT FK_IMPUGNAC_GENERA_IM_CASOETAP FOREIGN KEY (CASO_ETAPA_ID)
      REFERENCES CASOETAPA (CASO_ETAPA_ID)
);

CREATE INDEX GENERA_IMPUGNACION_FK ON IMPUGNACION (CASO_ETAPA_ID ASC);

CREATE SEQUENCE SEQ_IMPUGNACION START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_IMPUGNACION_ID
BEFORE INSERT ON IMPUGNACION
FOR EACH ROW
BEGIN
   IF :NEW.IMPUGNACION_ID IS NULL THEN
      SELECT SEQ_IMPUGNACION.NEXTVAL INTO :NEW.IMPUGNACION_ID FROM DUAL;
   END IF;
END;
/

/*==============================================================*/
/* Table: PAGO                                                  */
/*==============================================================*/
CREATE TABLE PAGO (
   PAGO_ID              NUMBER(6)             NOT NULL,
   CASO_ID              NUMBER(6)             NOT NULL,
   FECHA_PAGO           DATE,
   MONTO                NUMBER(14,2),
   FORMA_PAGO           VARCHAR2(50),
   NOTA                 CLOB,
   CONSTRAINT PK_PAGO PRIMARY KEY (PAGO_ID),
   CONSTRAINT FK_PAGO_REGISTRA__CASO FOREIGN KEY (CASO_ID)
      REFERENCES CASO (CASO_ID)
);

CREATE INDEX REGISTRA_PAGO_FK ON PAGO (CASO_ID ASC);

CREATE SEQUENCE SEQ_PAGO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PAGO_ID
BEFORE INSERT ON PAGO
FOR EACH ROW
BEGIN
   IF :NEW.PAGO_ID IS NULL THEN
      SELECT SEQ_PAGO.NEXTVAL INTO :NEW.PAGO_ID FROM DUAL;
   END IF;
END;
/

COMMIT;

PROMPT ========================================
PROMPT Schema creado exitosamente
PROMPT 14 tablas creadas
PROMPT 14 secuencias creadas
PROMPT 14 triggers creados
PROMPT ========================================
