-- ================================================================
-- Initial Data Seeding for InterfazBD1
-- ================================================================

-- 1. MASTER DATA (at least 3-5 records each)

-- TipoDocumento (5 records as required)
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('CC', 'Cedula de Ciudadania');
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('TI', 'Tarjeta de Identidad');
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('CE', 'Cedula de Extranjeria');
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('PA', 'Pasaporte');
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('RC', 'Registro Civil');

-- TipoContacto
INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('CEL', 'Celular');
INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('EMA', 'Email');
INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('DIR', 'Direccion Fisica');
INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('TEL', 'Telefono Fijo');
INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('WHA', 'WhatsApp');

-- TipoLugar
INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (1, 'Juzgado');
INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (2, 'Tribunal');
INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (3, 'Corte');
INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (4, 'Fiscalia');
INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (5, 'Notaria');

-- FormaPago
INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('EFE', 'Efectivo');
INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('TC', 'Tarjeta de Credito');
INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('TRA', 'Transferencia Bancaria');
INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('CHE', 'Cheque');
INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('PSE', 'PSE');

-- Franquicia
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('VIS', 'Visa');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('MAS', 'Mastercard');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('AME', 'American Express');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('DIN', 'Diners Club');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('COD', 'Codensa');

-- Instancia
INSERT INTO INSTANCIA (NINSTANCIA, DESCINSTANCIA) VALUES (1, 'Primera');
INSERT INTO INSTANCIA (NINSTANCIA, DESCINSTANCIA) VALUES (2, 'Segunda');
INSERT INTO INSTANCIA (NINSTANCIA, DESCINSTANCIA) VALUES (3, 'Tercera');

-- ================================================================
-- 2. PROCESS CONFIGURATION DATA
-- ================================================================

-- Especializacion (5 as required)
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('PEN', 'Penal');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('CIV', 'Civil');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('LAB', 'Laboral');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('ADM', 'Administrativo');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('FAM', 'Familia');

-- EtapaProcesal with ORDEN (for sequential logic)
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('IND', 'Indagacion', 1);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('IMP', 'Imputacion', 2);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('ACU', 'Acusacion', 3);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('JUI', 'Juicio', 4);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('SEN', 'Sentencia', 5);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('IMG', 'Impugnacion', 6);

-- Impugnacion
INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('RE', 'Reposicion');
INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('AP', 'Apelacion');
INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('CA', 'Casacion');
INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('QU', 'Queja');
INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('RV', 'Revision');

-- ================================================================
-- 3. ESPECIA-ETAPA Configuration
-- ================================================================


-- Penal Process Flow (corregido)
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES ('PEN', 1, NULL, 'SEN', NULL);
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES ('PEN', 2, 1, 'IMG', 'AP');

-- Civil Process Flow
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES ('CIV', 1, NULL, 'SEN', NULL);
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES ('CIV', 2, 1, 'IMG', 'AP');

-- Laboral Process Flow
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES ('LAB', 1, NULL, 'SEN', NULL);

-- Administrativo Process Flow
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES ('ADM', 1, NULL, 'SEN', NULL);

-- Familia Process Flow
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES ('FAM', 1, NULL, 'SEN', NULL);

-- ================================================================
-- 4. LUGARES (Hierarchical: Corte > Tribunal > Juzgado)
-- ================================================================

-- Bogota
INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('BOG01', 3, NULL, 'Bogota', 'Calle 12 #7-65', '6012345678', 'info@corte.gov.co');


INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('TRB01', 2, 'BOG01', 'Tribunal Superior Bogota', 'Carrera 10 #20-30', '6017654321', 'tribunal.bog@gov.co');

INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('TRB03', 2, 'BOG01', 'Tribunal Administrativo Cund', 'Calle 26 #50-00', '6019876543', 'tribunal.admin@gov.co');

INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('JZ001', 1, 'TRB01', 'Juzgado Penal Circuito 01', 'Av. Jimenez #8-43', '6015555555', 'juzgado01@gov.co');

INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('JZ002', 1, 'TRB01', 'Juzgado Civil Circuito 05', 'Calle 26 #51-20', '6015555556', 'juzgado05@gov.co');

-- Medellin
INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('MED01', 3, NULL, 'Medellin', 'Carrera 43 #57-41', '6044123456', 'info@medellin.gov.co');


INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('TRB02', 2, 'MED01', 'Tribunal Superior Medellin', 'Calle 44 #52-165', '6047654321', 'tribunal.med@gov.co');

INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('JZ003', 1, 'TRB02', 'Juzgado Laboral Circuito 03', 'Carrera 49 #50-21', '6045555557', 'juzgado03@gov.co');

-- ================================================================
-- 5. LAWYERS (5 as required)
-- ================================================================

INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1001', 'Pedro', 'Gomez', 'TP001');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1002', 'Maria', 'Rodriguez', 'TP002');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1003', 'Carlos', 'Lopez', 'TP003');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1004', 'Ana', 'Martinez', 'TP004');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1005', 'Luis', 'Sanchez', 'TP005');

-- Lawyer Specializations
INSERT INTO FK_ABOGADO_ESPECIAL (CODESPECIALIZACION, CEDULA) VALUES ('PEN', '1001'); 
INSERT INTO FK_ABOGADO_ESPECIAL (CODESPECIALIZACION, CEDULA) VALUES ('CIV', '1002'); 
INSERT INTO FK_ABOGADO_ESPECIAL (CODESPECIALIZACION, CEDULA) VALUES ('PEN', '1003'); 
INSERT INTO FK_ABOGADO_ESPECIAL (CODESPECIALIZACION, CEDULA) VALUES ('LAB', '1004'); 
INSERT INTO FK_ABOGADO_ESPECIAL (CODESPECIALIZACION, CEDULA) VALUES ('FAM', '1005'); 

-- ================================================================
-- 6. CLIENTS (5 as required)
-- ================================================================

INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C001', 'CC', 'Juan', 'Perez', '80123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C002', 'CC', 'Laura', 'Garcia', '52123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C003', 'CE', 'Andres', 'Torres', '79123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C004', 'TI', 'Sofia', 'Vargas', '10123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C005', 'CC', 'Diego', 'Rios', '90123456');

-- ================================================================
-- 7. TEST CASES with EXPEDIENTE
-- ================================================================

-- Case 1: Juan Perez - Penal (Active, with 3 stages completed)
INSERT INTO CASO (NOCASO, CODCLIENTE, CODESPECIALIZACION, FECHAINICIO, FECHAFIN, VALOR)
VALUES (1, 'C001', 'PEN', SYSDATE-60, NULL, '5000000');


INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (1, 'PEN', 1, 1, NULL, 'JZ001', SYSDATE-50); 

INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (1, 'PEN', 1, 2, '1001', 'JZ001', SYSDATE-40); 

INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (1, 'PEN', 1, 3, '1001', 'JZ001', SYSDATE-20); 

-- Case 2: Laura Garcia - Civil (Just started)
INSERT INTO CASO (NOCASO, CODCLIENTE, CODESPECIALIZACION, FECHAINICIO, FECHAFIN, VALOR)
VALUES (2, 'C002', 'CIV', SYSDATE-10, NULL, '8000000');


INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (2, 'CIV', 1, 1, '1002', 'JZ002', SYSDATE-5); 

-- Case 3: Andres Torres - Closed Penal case (to test read-only logic)
INSERT INTO CASO (NOCASO, CODCLIENTE, CODESPECIALIZACION, FECHAINICIO, FECHAFIN, VALOR)
VALUES (3, 'C003', 'PEN', SYSDATE-200, SYSDATE-30, '3000000');


INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (3, 'PEN', 1, 1, '1003', 'JZ001', SYSDATE-190);

INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (3, 'PEN', 1, 2, '1003', 'JZ001', SYSDATE-180);

INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (3, 'PEN', 1, 3, '1003', 'JZ001', SYSDATE-50); 

-- Test Case for Impugnacion (Instance 2)
-- Case 1: Penal, adding stage 4 as Impugnacion
INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA)
VALUES (1, 'PEN', 2, 4, '1001', 'TRB01', SYSDATE);

COMMIT;
