-- Initial Data Seeding

-- 1. Master Data
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('CC', 'Cedula de Ciudadania');
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('TI', 'Tarjeta de Identidad');
INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES ('CE', 'Cedula de Extranjeria');

INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('CEL', 'Celular');
INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('EMA', 'Email');
INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES ('DIR', 'Direccion Fisica');

INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (1, 'Juzgado');
INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (2, 'Tribunal');
INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (3, 'Corte');

INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('EFE', 'Efectivo');
INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('TC', 'Tarjeta de Credito');
INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES ('TRA', 'Transferencia');

INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('VIS', 'Visa');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('MAS', 'Mastercard');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES ('AME', 'American Express');

INSERT INTO INSTANCIA (NINSTANCIA) VALUES (1);
INSERT INTO INSTANCIA (NINSTANCIA) VALUES (2);
INSERT INTO INSTANCIA (NINSTANCIA) VALUES (3);

-- 2. Process Data
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('PEN', 'Penal');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('CIV', 'Civil');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('LAB', 'Laboral');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('ADM', 'Administrativo');
INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES ('FAM', 'Familia');

-- Etapas with Order
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('IND', 'Indagacion', 1);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('IMP', 'Imputacion', 2);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('ACU', 'Acusacion', 3);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('JUI', 'Juicio', 4);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('SEN', 'Sentencia', 5);
INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA, ORDEN) VALUES ('IMG', 'Impugnacion', 6);

INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('RE', 'Reposicion');
INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('AP', 'Apelacion');
INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES ('CA', 'Casacion');

-- 3. Configuration (Especia-Etapa) - Penal
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) 
VALUES ('PEN', 1, NULL, 'IND', NULL);
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) 
VALUES ('PEN', 1, NULL, 'IMP', NULL);
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) 
VALUES ('PEN', 1, NULL, 'ACU', NULL);
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) 
VALUES ('PEN', 1, NULL, 'JUI', NULL);
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) 
VALUES ('PEN', 1, 2, 'SEN', NULL);
INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, NINSTANCIA, INS_NINSTANCIA, CODETAPA, IDIMPUGNA) 
VALUES ('PEN', 2, 3, 'IMG', 'AP');

-- 4. Locations (Hierarchy)
INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('BOG', 3, NULL, 'Corte Suprema Bogota', 'Calle 123', '1234567', 'corte@gov.co');

INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('TRI01', 2, 'BOG', 'Tribunal Superior Bogota', 'Carrera 456', '7654321', 'tribunal@gov.co');

INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, LUG_CODLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR)
VALUES ('JUZ01', 1, 'TRI01', 'Juzgado Penal Circuito 01', 'Avenida 789', '5555555', 'juzgado01@gov.co');

-- 5. People
-- Lawyers
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1001', 'Pedro', 'Gomez', 'TP001');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1002', 'Maria', 'Rodriguez', 'TP002');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1003', 'Carlos', 'Lopez', 'TP003');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1004', 'Ana', 'Martinez', 'TP004');
INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES ('1005', 'Luis', 'Sanchez', 'TP005');

INSERT INTO FK_ABOGADO_ESPECIAL (CODESPECIALIZACION, CEDULA) VALUES ('PEN', '1001'); -- Pedro is Penalista

-- Clients
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C001', 'CC', 'Juan', 'Perez', '80123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C002', 'CC', 'Laura', 'Gacia', '52123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C003', 'CC', 'Andres', 'Torres', '79123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C004', 'CC', 'Sofia', 'Vargas', '10123456');
INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELLCLIENTE, NDOCUMENTO) 
VALUES ('C005', 'CC', 'Diego', 'Rios', '90123456');

-- 6. Hypothetical Case (Juan Perez - Hurto Agravado)
-- Case
INSERT INTO CASO (NOCASO, CODCLIENTE, CODESPECIALIZACION, FECHAINICIO, VALOR)
VALUES (1, 'C001', 'PEN', SYSDATE, '5000000');

-- Expediente (Stages)
-- 1. Indagacion
-- Note: PASOETAPA should link to ID_ESPECIA_ETAPA. Since IDs are generated, we can't hardcode easily.
-- BUT for this script to work, we need to know the IDs or use a subquery.
-- Since this is initial data, we can assume sequence starts at 1.
-- Indagacion (PEN, 1, IND) -> ID 1
-- Imputacion (PEN, 1, IMP) -> ID 2
-- Acusacion (PEN, 1, ACU) -> ID 3
-- Juicio (PEN, 1, JUI) -> ID 4
-- Sentencia (PEN, 1, SEN) -> ID 5
-- Impugnacion (PEN, 2, IMG) -> ID 6

INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA, PASOETAPA)
VALUES (1, 'PEN', 1, 1, '1001', 'JUZ01', SYSDATE-30, 1);

INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA, PASOETAPA)
VALUES (1, 'PEN', 1, 2, '1001', 'JUZ01', SYSDATE-20, 2);

INSERT INTO EXPEDIENTE (NOCASO, CODESPECIALIZACION, NINSTANCIA, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA, PASOETAPA)
VALUES (1, 'PEN', 1, 3, '1001', 'JUZ01', SYSDATE-10, 3);

COMMIT;
